
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `cormatrix`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2020, 
        `title`="seolmatrix", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/cormatrix/", 
        `url`="https://github.com/hyunsooseol/cormatrix/"), 
    `psych`=list(
        `type`="software", 
        `author`="William Revelle", 
        `year`=2019, 
        `title`="psych: Procedures for Personality and Psychological Research", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=psych", 
        `url`="https://CRAN.R-project.org/package=psych"))
