
# This file is automatically generated, you probably don't want to edit this

ahpsurveyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ahpsurveyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            atts = "cult, fam, house, jobs, trans",
            ap = FALSE,
            method = "eigen",
            aj = FALSE,
            method1 = "geometric",
            plot1 = TRUE, ...) {

            super$initialize(
                package="seolmatrix",
                name="ahpsurvey",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..atts <- jmvcore::OptionString$new(
                "atts",
                atts,
                default="cult, fam, house, jobs, trans")
            private$..ap <- jmvcore::OptionBool$new(
                "ap",
                ap,
                default=FALSE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "eigen",
                    "geometric",
                    "arithmetic",
                    "rootmean"),
                default="eigen")
            private$..aj <- jmvcore::OptionBool$new(
                "aj",
                aj,
                default=FALSE)
            private$..method1 <- jmvcore::OptionList$new(
                "method1",
                method1,
                options=list(
                    "geometric",
                    "arithmetic",
                    "rootmean"),
                default="geometric")
            private$..cr <- jmvcore::OptionOutput$new(
                "cr")
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..atts)
            self$.addOption(private$..ap)
            self$.addOption(private$..method)
            self$.addOption(private$..aj)
            self$.addOption(private$..method1)
            self$.addOption(private$..cr)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        atts = function() private$..atts$value,
        ap = function() private$..ap$value,
        method = function() private$..method$value,
        aj = function() private$..aj$value,
        method1 = function() private$..method1$value,
        cr = function() private$..cr$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..atts = NA,
        ..ap = NA,
        ..method = NA,
        ..aj = NA,
        ..method1 = NA,
        ..cr = NA,
        ..plot1 = NA)
)

ahpsurveyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ahpsurveyResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        plot1 = function() private$.items[["plot1"]],
        ap = function() private$.items[["ap"]],
        aj = function() private$.items[["aj"]],
        cr = function() private$.items[["cr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="AHP for survey data",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="AHP for survey data"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Individual preference weights",
                visible="(plot1)",
                width=600,
                height=400,
                renderFun=".plot1",
                refs="ahpsurvey",
                clearWith=list(
                    "vars")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ap",
                title="Aggregated priorities",
                visible="(ap)",
                refs="ahpsurvey",
                clearWith=list(
                    "vars",
                    "method"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="value", 
                        `title`="Value"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="aj",
                title="Aggregated individual judgements",
                refs="ahpsurvey",
                visible="(aj)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="cr",
                title="CR",
                varTitle="CR",
                measureType="continuous",
                clearWith=list(
                    "vars")))}))

ahpsurveyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ahpsurveyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "ahpsurvey",
                version = c(1,0,0),
                options = options,
                results = ahpsurveyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' AHP for survey data
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param atts .
#' @param ap .
#' @param method .
#' @param aj .
#' @param method1 .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ap} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$aj} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cr} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ap$asDF}
#'
#' \code{as.data.frame(results$ap)}
#'
#' @export
ahpsurvey <- function(
    data,
    vars,
    atts = "cult, fam, house, jobs, trans",
    ap = FALSE,
    method = "eigen",
    aj = FALSE,
    method1 = "geometric",
    plot1 = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ahpsurvey requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- ahpsurveyOptions$new(
        vars = vars,
        atts = atts,
        ap = ap,
        method = method,
        aj = aj,
        method1 = method1,
        plot1 = plot1)

    analysis <- ahpsurveyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

