
# This file is automatically generated, you probably don't want to edit this

ccOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ccOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            set1 = NULL,
            set2 = NULL,
            cor = TRUE,
            test = FALSE,
            coef = FALSE,
            load = FALSE,
            cross = FALSE,
            redun = FALSE,
            plot = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="cc",
                requiresData=TRUE,
                ...)

            private$..set1 <- jmvcore::OptionVariables$new(
                "set1",
                set1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..set2 <- jmvcore::OptionVariables$new(
                "set2",
                set2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cor <- jmvcore::OptionBool$new(
                "cor",
                cor,
                default=TRUE)
            private$..test <- jmvcore::OptionBool$new(
                "test",
                test,
                default=FALSE)
            private$..coef <- jmvcore::OptionBool$new(
                "coef",
                coef,
                default=FALSE)
            private$..load <- jmvcore::OptionBool$new(
                "load",
                load,
                default=FALSE)
            private$..cross <- jmvcore::OptionBool$new(
                "cross",
                cross,
                default=FALSE)
            private$..redun <- jmvcore::OptionBool$new(
                "redun",
                redun,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..scores <- jmvcore::OptionOutput$new(
                "scores")

            self$.addOption(private$..set1)
            self$.addOption(private$..set2)
            self$.addOption(private$..cor)
            self$.addOption(private$..test)
            self$.addOption(private$..coef)
            self$.addOption(private$..load)
            self$.addOption(private$..cross)
            self$.addOption(private$..redun)
            self$.addOption(private$..plot)
            self$.addOption(private$..scores)
        }),
    active = list(
        set1 = function() private$..set1$value,
        set2 = function() private$..set2$value,
        cor = function() private$..cor$value,
        test = function() private$..test$value,
        coef = function() private$..coef$value,
        load = function() private$..load$value,
        cross = function() private$..cross$value,
        redun = function() private$..redun$value,
        plot = function() private$..plot$value,
        scores = function() private$..scores$value),
    private = list(
        ..set1 = NA,
        ..set2 = NA,
        ..cor = NA,
        ..test = NA,
        ..coef = NA,
        ..load = NA,
        ..cross = NA,
        ..redun = NA,
        ..plot = NA,
        ..scores = NA)
)

ccResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ccResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        cor = function() private$.items[["cor"]],
        test = function() private$.items[["test"]],
        coef = function() private$.items[["coef"]],
        load = function() private$.items[["load"]],
        cross = function() private$.items[["cross"]],
        redun = function() private$.items[["redun"]],
        plot = function() private$.items[["plot"]],
        scores = function() private$.items[["scores"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Canonical Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="cor",
                title="Canonical correlations",
                visible="(cor)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="func", 
                        `title`="Function", 
                        `type`="integer"),
                    list(
                        `name`="canonicalCorrelation", 
                        `title`="Canonical correlation", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="variance", 
                        `title`="Variance explained", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="test",
                title="Significance tests",
                visible="(test)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="testFunc", 
                        `title`="Function(s)", 
                        `type`="text"),
                    list(
                        `name`="wilks", 
                        `title`="Wilks' Lambda", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="chisq", 
                        `title`="Chi-square", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="Canonical coefficients for standardized variables",
                visible="(coef)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="set", 
                        `title`="Set", 
                        `type`="text"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="func", 
                        `title`="Function", 
                        `type`="integer"),
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="load",
                title="Canonical loadings",
                visible="(load)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="set", 
                        `title`="Set", 
                        `type`="text"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="func", 
                        `title`="Function", 
                        `type`="integer"),
                    list(
                        `name`="loading", 
                        `title`="Loading", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cross",
                title="Cross-loadings",
                visible="(cross)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="set", 
                        `title`="Set", 
                        `type`="text"),
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="func", 
                        `title`="Function", 
                        `type`="integer"),
                    list(
                        `name`="crossLoading", 
                        `title`="Cross-loading", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="redun",
                title="Redundancy analysis",
                visible="(redun)",
                clearWith=list(
                    "set1",
                    "set2"),
                columns=list(
                    list(
                        `name`="set", 
                        `title`="Set", 
                        `type`="text"),
                    list(
                        `name`="func", 
                        `title`="Function", 
                        `type`="integer"),
                    list(
                        `name`="varianceExtracted", 
                        `title`="Variance extracted", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="redundancy", 
                        `title`="Redundancy", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Canonical correlation plot",
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "set1",
                    "set2")))
            self$add(jmvcore::Output$new(
                options=options,
                name="scores",
                title="Canonical scores",
                clearWith=list(
                    "set1",
                    "set2")))}))

ccBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ccBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "cc",
                version = c(1,0,0),
                options = options,
                results = ccResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Canonical Correlation
#'
#' 
#' @param data .
#' @param set1 .
#' @param set2 .
#' @param cor .
#' @param test .
#' @param coef .
#' @param load .
#' @param cross .
#' @param redun .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cor} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$test} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$load} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cross} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$redun} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$scores} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cor$asDF}
#'
#' \code{as.data.frame(results$cor)}
#'
#' @export
cc <- function(
    data,
    set1,
    set2,
    cor = TRUE,
    test = FALSE,
    coef = FALSE,
    load = FALSE,
    cross = FALSE,
    redun = FALSE,
    plot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(set1)) set1 <- jmvcore::resolveQuo(jmvcore::enquo(set1))
    if ( ! missing(set2)) set2 <- jmvcore::resolveQuo(jmvcore::enquo(set2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(set1), set1, NULL),
            `if`( ! missing(set2), set2, NULL))


    options <- ccOptions$new(
        set1 = set1,
        set2 = set2,
        cor = cor,
        test = test,
        coef = coef,
        load = load,
        cross = cross,
        redun = redun,
        plot = plot)

    analysis <- ccClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

