
# This file is automatically generated, you probably don't want to edit this

concordanceOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "concordanceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            cc = TRUE,
            ccp = FALSE, ...) {

            super$initialize(
                package='seolmatrix',
                name='concordance',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariable$new(
                "covs",
                covs,
                permitted=list(
                    "numeric"))
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=TRUE)
            private$..ccp <- jmvcore::OptionBool$new(
                "ccp",
                ccp,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..cc)
            self$.addOption(private$..ccp)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        cc = function() private$..cc$value,
        ccp = function() private$..ccp$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..cc = NA,
        ..ccp = NA)
)

concordanceResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        table = function() private$.items[["table"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Concordance Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Estimated Correlation",
                rows=1,
                refs="epiR",
                columns=list(
                    list(
                        `name`="r", 
                        `title`="Concordance", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Concordance Plot",
                width=400,
                height=400,
                renderFun=".plot",
                visible="(ccp)",
                refs="epiR"))}))

concordanceBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "concordanceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'seolmatrix',
                name = 'concordance',
                version = c(1,0,0),
                options = options,
                results = concordanceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Concordance Correlation
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param cc .
#' @param ccp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
concordance <- function(
    data,
    dep,
    covs,
    cc = TRUE,
    ccp = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('concordance requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))


    options <- concordanceOptions$new(
        dep = dep,
        covs = covs,
        cc = cc,
        ccp = ccp)

    analysis <- concordanceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
