
# This file is automatically generated, you probably don't want to edit this

concordanceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "concordanceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            dep = NULL,
            covs = NULL,
            id = NULL,
            cc = FALSE,
            mat = FALSE,
            ccp = FALSE,
            bap = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="seolmatrix",
                name="concordance",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "continuous"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariable$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=FALSE)
            private$..mat <- jmvcore::OptionBool$new(
                "mat",
                mat,
                default=FALSE)
            private$..ccp <- jmvcore::OptionBool$new(
                "ccp",
                ccp,
                default=FALSE)
            private$..bap <- jmvcore::OptionBool$new(
                "bap",
                bap,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..id)
            self$.addOption(private$..cc)
            self$.addOption(private$..mat)
            self$.addOption(private$..ccp)
            self$.addOption(private$..bap)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        id = function() private$..id$value,
        cc = function() private$..cc$value,
        mat = function() private$..mat$value,
        ccp = function() private$..ccp$value,
        bap = function() private$..bap$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..dep = NA,
        ..covs = NA,
        ..id = NA,
        ..cc = NA,
        ..mat = NA,
        ..ccp = NA,
        ..bap = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA)
)

concordanceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "concordanceResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        cc = function() private$.items[["cc"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        mat = function() private$.items[["mat"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Concordance Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="cc",
                title="Estimated Correlation",
                rows=1,
                refs="epiR",
                clearWith=list(
                    "dep",
                    "covs",
                    "id"),
                columns=list(
                    list(
                        `name`="r", 
                        `title`="Concordance", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Concordance Plot",
                renderFun=".plot",
                visible="(ccp)",
                clearWith=list(
                    "dep",
                    "covs",
                    "width",
                    "height",
                    "id"),
                refs="epiR"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Bland-Altman Plot",
                renderFun=".plot1",
                visible="(bap)",
                clearWith=list(
                    "dep",
                    "covs",
                    "width1",
                    "height1",
                    "id"),
                refs="epiR"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mat",
                title="Concordance matrix",
                visible="(mat)",
                clearWith=list(
                    "vars",
                    "id"),
                refs="epiR",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))}))

concordanceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "concordanceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "concordance",
                version = c(1,0,0),
                options = options,
                results = concordanceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Concordance Correlation
#'
#' 
#' @param data .
#' @param vars .
#' @param dep .
#' @param covs .
#' @param id .
#' @param cc .
#' @param mat .
#' @param ccp .
#' @param bap .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mat} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cc$asDF}
#'
#' \code{as.data.frame(results$cc)}
#'
#' @export
concordance <- function(
    data,
    vars,
    dep,
    covs,
    id,
    cc = FALSE,
    mat = FALSE,
    ccp = FALSE,
    bap = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("concordance requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(id), id, NULL))

    for (v in id) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- concordanceOptions$new(
        vars = vars,
        dep = dep,
        covs = covs,
        id = id,
        cc = cc,
        mat = mat,
        ccp = ccp,
        bap = bap,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1)

    analysis <- concordanceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

