
# This file is automatically generated, you probably don't want to edit this

corOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "pearson",
            mat = TRUE,
            missing = "pairwise.complete.obs",
            order = "hclust",
            method = "complete",
            k = 2,
            size = 3,
            color = "blue",
            plot = FALSE,
            method1 = "circle",
            type1 = "full",
            width = 500,
            height = 500, ...) {

            super$initialize(
                package="seolmatrix",
                name="cor",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson")
            private$..mat <- jmvcore::OptionBool$new(
                "mat",
                mat,
                default=TRUE)
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "complete.obs",
                    "pairwise.complete.obs"),
                default="pairwise.complete.obs")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "hclust",
                    "AOE",
                    "FPC",
                    "alphabet",
                    "original"),
                default="hclust")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "complete",
                    "ward",
                    "ward.D",
                    "ward.D2",
                    "single",
                    "average",
                    "mcquitty",
                    "median",
                    "centroid"),
                default="complete")
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                min=1,
                default=2)
            private$..size <- jmvcore::OptionInteger$new(
                "size",
                size,
                default=3)
            private$..color <- jmvcore::OptionList$new(
                "color",
                color,
                options=list(
                    "black",
                    "red",
                    "blue",
                    "green",
                    "purple",
                    "orange",
                    "navy"),
                default="blue")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..method1 <- jmvcore::OptionList$new(
                "method1",
                method1,
                options=list(
                    "circle",
                    "square",
                    "ellipse",
                    "number",
                    "shade",
                    "color",
                    "pie"),
                default="circle")
            private$..type1 <- jmvcore::OptionList$new(
                "type1",
                type1,
                options=list(
                    "full",
                    "lower",
                    "upper"),
                default="full")
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..mat)
            self$.addOption(private$..missing)
            self$.addOption(private$..order)
            self$.addOption(private$..method)
            self$.addOption(private$..k)
            self$.addOption(private$..size)
            self$.addOption(private$..color)
            self$.addOption(private$..plot)
            self$.addOption(private$..method1)
            self$.addOption(private$..type1)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        mat = function() private$..mat$value,
        missing = function() private$..missing$value,
        order = function() private$..order$value,
        method = function() private$..method$value,
        k = function() private$..k$value,
        size = function() private$..size$value,
        color = function() private$..color$value,
        plot = function() private$..plot$value,
        method1 = function() private$..method1$value,
        type1 = function() private$..type1$value,
        width = function() private$..width$value,
        height = function() private$..height$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..mat = NA,
        ..missing = NA,
        ..order = NA,
        ..method = NA,
        ..k = NA,
        ..size = NA,
        ..color = NA,
        ..plot = NA,
        ..method1 = NA,
        ..type1 = NA,
        ..width = NA,
        ..height = NA)
)

corResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation Structure",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="`Correlation matrix - ${type}`",
                visible="(matrix)",
                clearWith=list(
                    "vars",
                    "type",
                    "missing"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Hierarchical clustering",
                visible="(plot)",
                refs="corrplot",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "k",
                    "type",
                    "method",
                    "size",
                    "missing",
                    "color",
                    "order",
                    "method1",
                    "type1",
                    "width",
                    "height")))}))

corBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "cor",
                version = c(1,0,0),
                options = options,
                results = corResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correlation Structure
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param mat .
#' @param missing .
#' @param order .
#' @param method .
#' @param k .
#' @param size .
#' @param color .
#' @param plot .
#' @param method1 .
#' @param type1 .
#' @param width .
#' @param height .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
cor <- function(
    data,
    vars,
    type = "pearson",
    mat = TRUE,
    missing = "pairwise.complete.obs",
    order = "hclust",
    method = "complete",
    k = 2,
    size = 3,
    color = "blue",
    plot = FALSE,
    method1 = "circle",
    type1 = "full",
    width = 500,
    height = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cor requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- corOptions$new(
        vars = vars,
        type = type,
        mat = mat,
        missing = missing,
        order = order,
        method = method,
        k = k,
        size = size,
        color = color,
        plot = plot,
        method1 = method1,
        type1 = type1,
        width = width,
        height = height)

    analysis <- corClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

