
# This file is automatically generated, you probably don't want to edit this

corOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "pearson",
            method = "ward.D",
            k = 2,
            size = 3,
            plot = TRUE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="cor",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pearson",
                    "spearman",
                    "tetra",
                    "poly"),
                default="pearson")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "ward.D",
                    "ward.D2",
                    "single",
                    "complete",
                    "average",
                    "mcquitty",
                    "median",
                    "centroid"),
                default="ward.D")
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..size <- jmvcore::OptionInteger$new(
                "size",
                size,
                default=3)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..method)
            self$.addOption(private$..k)
            self$.addOption(private$..size)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        method = function() private$..method$value,
        k = function() private$..k$value,
        size = function() private$..size$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..method = NA,
        ..k = NA,
        ..size = NA,
        ..plot = NA,
        ..plot1 = NA)
)

corResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation structure")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Correlation structure"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Correlation heat map",
                visible="(plot)",
                width=600,
                height=600,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "k",
                    "type",
                    "method",
                    "size")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Dendrogram",
                visible="(plot1)",
                width=600,
                height=600,
                renderFun=".plot1",
                clearWith=list(
                    "vars",
                    "k",
                    "type",
                    "method",
                    "size")))}))

corBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "corBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "cor",
                version = c(1,0,0),
                options = options,
                results = corResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Correlation structure
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param method .
#' @param k .
#' @param size .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
cor <- function(
    data,
    vars,
    type = "pearson",
    method = "ward.D",
    k = 2,
    size = 3,
    plot = TRUE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cor requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- corOptions$new(
        vars = vars,
        type = type,
        method = method,
        k = k,
        size = size,
        plot = plot,
        plot1 = plot1)

    analysis <- corClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

