
# This file is automatically generated, you probably don't want to edit this

dichotomousOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dichotomousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            tetrachoric = TRUE,
            scale = "raw",
            plot = FALSE,
            plot1 = FALSE,
            plot2 = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="dichotomous",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..tetrachoric <- jmvcore::OptionBool$new(
                "tetrachoric",
                tetrachoric,
                default=TRUE)
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "raw",
                    "z-scores",
                    "relative"),
                default="raw")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..tetrachoric)
            self$.addOption(private$..scale)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
        }),
    active = list(
        vars = function() private$..vars$value,
        tetrachoric = function() private$..tetrachoric$value,
        scale = function() private$..scale$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value),
    private = list(
        ..vars = NA,
        ..tetrachoric = NA,
        ..scale = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA)
)

dichotomousResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dichotomousResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]],
        plot2 = function() private$.items[["plot2"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Tetrachoric Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Tetrachoric Correlation",
                visible="(matrix)",
                refs="psych",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(plot)",
                refs="qgraph",
                clearWith=list(
                    "vars")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Centrality plot ",
                width=500,
                height=500,
                renderFun=".plot2",
                visible="(plot2)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "scale")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Partial plot",
                width=500,
                height=500,
                renderFun=".plot1",
                visible="(plot1)",
                refs="qgraph",
                clearWith=list(
                    "vars")))}))

dichotomousBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "dichotomousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "dichotomous",
                version = c(1,0,0),
                options = options,
                results = dichotomousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Tetrachoric Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param tetrachoric .
#' @param scale .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
dichotomous <- function(
    data,
    vars,
    tetrachoric = TRUE,
    scale = "raw",
    plot = FALSE,
    plot1 = FALSE,
    plot2 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dichotomous requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- dichotomousOptions$new(
        vars = vars,
        tetrachoric = tetrachoric,
        scale = scale,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2)

    analysis <- dichotomousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

