
# This file is automatically generated, you probably don't want to edit this

kappaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kappaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            fk = FALSE,
            ek = FALSE,
            cw = FALSE,
            krip = FALSE,
            method = "nominal", ...) {

            super$initialize(
                package="seolmatrix",
                name="kappa",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..fk <- jmvcore::OptionBool$new(
                "fk",
                fk,
                default=FALSE)
            private$..ek <- jmvcore::OptionBool$new(
                "ek",
                ek,
                default=FALSE)
            private$..cw <- jmvcore::OptionBool$new(
                "cw",
                cw,
                default=FALSE)
            private$..krip <- jmvcore::OptionBool$new(
                "krip",
                krip,
                default=FALSE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "nominal",
                    "ordinal",
                    "interval",
                    "ratio"),
                default="nominal")

            self$.addOption(private$..vars)
            self$.addOption(private$..fk)
            self$.addOption(private$..ek)
            self$.addOption(private$..cw)
            self$.addOption(private$..krip)
            self$.addOption(private$..method)
        }),
    active = list(
        vars = function() private$..vars$value,
        fk = function() private$..fk$value,
        ek = function() private$..ek$value,
        cw = function() private$..cw$value,
        krip = function() private$..krip$value,
        method = function() private$..method$value),
    private = list(
        ..vars = NA,
        ..fk = NA,
        ..ek = NA,
        ..cw = NA,
        ..krip = NA,
        ..method = NA)
)

kappaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kappaResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        fk = function() private$.items[["fk"]],
        ek = function() private$.items[["ek"]],
        cw = function() private$.items[["cw"]],
        krip = function() private$.items[["krip"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fleiss Kappa and Krippendorff alpha",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fk",
                title="Fleiss Kappa",
                rows=1,
                visible="(fk)",
                clearWith=list(
                    "vars"),
                refs="irr",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Fleiss' Kappa"),
                    list(
                        `name`="n", 
                        `type`="number"),
                    list(
                        `name`="rater", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ek",
                title="Exact Kappa",
                rows=1,
                visible="(ek)",
                clearWith=list(
                    "vars"),
                refs="irr",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Exact Kappa"),
                    list(
                        `name`="n", 
                        `type`="number"),
                    list(
                        `name`="rater", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cw",
                title="Category-wise kappas",
                visible="(cw)",
                refs="irr",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Category", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="k", 
                        `title`="Kappa", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `title`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="krip",
                title="Krippendorff alpha",
                rows=1,
                visible="(krip)",
                clearWith=list(
                    "vars"),
                refs="irr",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Krippendorff alpha"),
                    list(
                        `name`="Subjects", 
                        `type`="number"),
                    list(
                        `name`="Raters", 
                        `type`="number"),
                    list(
                        `name`="alpha", 
                        `type`="number"))))}))

kappaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kappaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "kappa",
                version = c(1,0,0),
                options = options,
                results = kappaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Fleiss Kappa and Krippendorff alpha
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param fk .
#' @param ek .
#' @param cw .
#' @param krip .
#' @param method .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fk} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ek} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cw} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$krip} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fk$asDF}
#'
#' \code{as.data.frame(results$fk)}
#'
#' @export
kappa <- function(
    data,
    vars,
    fk = FALSE,
    ek = FALSE,
    cw = FALSE,
    krip = FALSE,
    method = "nominal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("kappa requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- kappaOptions$new(
        vars = vars,
        fk = fk,
        ek = ek,
        cw = cw,
        krip = krip,
        method = method)

    analysis <- kappaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

