
# This file is automatically generated, you probably don't want to edit this

mapOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "pearson",
            eigen = TRUE,
            avgCorr = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="map",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pearson",
                    "kendall",
                    "spearman",
                    "gamma",
                    "polychoric"),
                default="pearson")
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..avgCorr <- jmvcore::OptionBool$new(
                "avgCorr",
                avgCorr,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..eigen)
            self$.addOption(private$..avgCorr)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        eigen = function() private$..eigen$value,
        avgCorr = function() private$..avgCorr$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..eigen = NA,
        ..avgCorr = NA)
)

mapResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        eigen = function() private$.items[["eigen"]],
        avgCorr = function() private$.items[["avgCorr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Velicer MAP Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Velicer MAP Test"))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Initial Eigenvalues",
                visible="(eigen)",
                clearWith=list(
                    "vars",
                    "type"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="integer"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalues", 
                        `type`="number"),
                    list(
                        `name`="propVar", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="cumVar", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="avgCorr",
                title="Velicer's Average Squared Correlations",
                visible="(avgCorr)",
                clearWith=list(
                    "vars",
                    "type"),
                columns=list(
                    list(
                        `name`="root", 
                        `title`="Root", 
                        `type`="integer"),
                    list(
                        `name`="avgSq", 
                        `title`="Avg.Corr.Sq.", 
                        `type`="number"),
                    list(
                        `name`="avgPow4", 
                        `title`="Avg.Corr.power4", 
                        `type`="number"))))}))

mapBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "map",
                version = c(1,0,0),
                options = options,
                results = mapResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Velicer MAP Test
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param eigen .
#' @param avgCorr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$avgCorr} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
map <- function(
    data,
    vars,
    type = "pearson",
    eigen = TRUE,
    avgCorr = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("map requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- mapOptions$new(
        vars = vars,
        type = type,
        eigen = eigen,
        avgCorr = avgCorr)

    analysis <- mapClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

