
# This file is automatically generated, you probably don't want to edit this

mapOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "pearson",
            eigen = TRUE,
            avgCorr = FALSE,
            screePlot = FALSE,
            MapCurvePlot = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500, ...) {

            super$initialize(
                package="seolmatrix",
                name="map",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pearson",
                    "kendall",
                    "spearman",
                    "gamma",
                    "polychoric"),
                default="pearson")
            private$..eigen <- jmvcore::OptionBool$new(
                "eigen",
                eigen,
                default=TRUE)
            private$..avgCorr <- jmvcore::OptionBool$new(
                "avgCorr",
                avgCorr,
                default=FALSE)
            private$..screePlot <- jmvcore::OptionBool$new(
                "screePlot",
                screePlot,
                default=FALSE)
            private$..MapCurvePlot <- jmvcore::OptionBool$new(
                "MapCurvePlot",
                MapCurvePlot,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..eigen)
            self$.addOption(private$..avgCorr)
            self$.addOption(private$..screePlot)
            self$.addOption(private$..MapCurvePlot)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        eigen = function() private$..eigen$value,
        avgCorr = function() private$..avgCorr$value,
        screePlot = function() private$..screePlot$value,
        MapCurvePlot = function() private$..MapCurvePlot$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..eigen = NA,
        ..avgCorr = NA,
        ..screePlot = NA,
        ..MapCurvePlot = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA)
)

mapResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        eigen = function() private$.items[["eigen"]],
        avgCorr = function() private$.items[["avgCorr"]],
        screePlot = function() private$.items[["screePlot"]],
        MapCurvePlot = function() private$.items[["MapCurvePlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Velicer MAP Test",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Velicer MAP Test"))
            self$add(jmvcore::Table$new(
                options=options,
                name="eigen",
                title="Initial Eigenvalues",
                visible="(eigen)",
                refs="EFA.dimensions",
                clearWith=list(
                    "vars",
                    "type"),
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="integer"),
                    list(
                        `name`="eigen", 
                        `title`="Eigenvalues", 
                        `type`="number"),
                    list(
                        `name`="propVar", 
                        `title`="% of Variance", 
                        `type`="number"),
                    list(
                        `name`="cumVar", 
                        `title`="Cumulative %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="avgCorr",
                title="Velicer's Average Squared Correlations",
                visible="(avgCorr)",
                refs="EFA.dimensions",
                clearWith=list(
                    "vars",
                    "type"),
                columns=list(
                    list(
                        `name`="root", 
                        `title`="Root", 
                        `type`="integer"),
                    list(
                        `name`="avgSq", 
                        `title`="Average Squared Correlations", 
                        `type`="number"),
                    list(
                        `name`="avgPow4", 
                        `title`="Average Squared Correlations (Fourth Power)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="screePlot",
                title="Scree Plot (Initial Eigenvalues)",
                renderFun=".screePlot",
                visible="(screePlot)",
                clearWith=list(
                    "vars",
                    "type",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="MapCurvePlot",
                title="MAP Curves (Average Squared Correlations)",
                renderFun=".MapCurvePlot",
                visible="(MapCurvePlot)",
                clearWith=list(
                    "vars",
                    "type",
                    "width1",
                    "height1")))}))

mapBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mapBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "map",
                version = c(1,0,0),
                options = options,
                results = mapResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Velicer MAP Test
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param eigen .
#' @param avgCorr .
#' @param screePlot .
#' @param MapCurvePlot .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$avgCorr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$screePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$MapCurvePlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$eigen$asDF}
#'
#' \code{as.data.frame(results$eigen)}
#'
#' @export
map <- function(
    data,
    vars,
    type = "pearson",
    eigen = TRUE,
    avgCorr = FALSE,
    screePlot = FALSE,
    MapCurvePlot = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("map requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- mapOptions$new(
        vars = vars,
        type = type,
        eigen = eigen,
        avgCorr = avgCorr,
        screePlot = screePlot,
        MapCurvePlot = MapCurvePlot,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1)

    analysis <- mapClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

