
# This file is automatically generated, you probably don't want to edit this

multilevelOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multilevelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            facs = NULL,
            vars = NULL,
            multi = TRUE, ...) {

            super$initialize(
                package='seolmatrix',
                name='multilevel',
                requiresData=TRUE,
                ...)

            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..multi <- jmvcore::OptionBool$new(
                "multi",
                multi,
                default=TRUE)

            self$.addOption(private$..facs)
            self$.addOption(private$..vars)
            self$.addOption(private$..multi)
        }),
    active = list(
        facs = function() private$..facs$value,
        vars = function() private$..vars$value,
        multi = function() private$..multi$value),
    private = list(
        ..facs = NA,
        ..vars = NA,
        ..multi = NA)
)

multilevelResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        multi = function() private$.items[["multi"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="correlation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="multi",
                title="Multilevel Correlation",
                visible="(multi)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="v1", 
                        `title`="Variable1", 
                        `type`="text"),
                    list(
                        `name`="v2", 
                        `title`="Variable2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="n", 
                        `type`="integer"),
                    list(
                        `name`="low", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="high", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))}))

multilevelBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "multilevelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'seolmatrix',
                name = 'multilevel',
                version = c(1,0,0),
                options = options,
                results = multilevelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multilevel Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param facs .
#' @param vars .
#' @param multi .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$multi} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$multi$asDF}
#'
#' \code{as.data.frame(results$multi)}
#'
#' @export
multilevel <- function(
    data,
    facs,
    vars,
    multi = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('multilevel requires jmvcore to be installed (restart may be required)')

    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(facs), facs, NULL),
            `if`( ! missing(vars), vars, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multilevelOptions$new(
        facs = facs,
        vars = vars,
        multi = multi)

    analysis <- multilevelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
