
# This file is automatically generated, you probably don't want to edit this

multilevelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            facs = NULL,
            icc = TRUE,
            multi = FALSE,
            plot = FALSE,
            angle = 45, ...) {

            super$initialize(
                package="seolmatrix",
                name="multilevel",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..facs <- jmvcore::OptionVariable$new(
                "facs",
                facs,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..icc <- jmvcore::OptionBool$new(
                "icc",
                icc,
                default=TRUE)
            private$..multi <- jmvcore::OptionBool$new(
                "multi",
                multi,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=45)

            self$.addOption(private$..vars)
            self$.addOption(private$..facs)
            self$.addOption(private$..icc)
            self$.addOption(private$..multi)
            self$.addOption(private$..plot)
            self$.addOption(private$..angle)
        }),
    active = list(
        vars = function() private$..vars$value,
        facs = function() private$..facs$value,
        icc = function() private$..icc$value,
        multi = function() private$..multi$value,
        plot = function() private$..plot$value,
        angle = function() private$..angle$value),
    private = list(
        ..vars = NA,
        ..facs = NA,
        ..icc = NA,
        ..multi = NA,
        ..plot = NA,
        ..angle = NA)
)

multilevelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        icc = function() private$.items[["icc"]],
        multi = function() private$.items[["multi"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multilevel Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="icc",
                title="Intraclass correlation coefficient from ANOVA",
                rows="(vars)",
                visible="(icc)",
                clearWith=list(
                    "vars",
                    "facs"),
                refs="multilevel",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Variables", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="icc1", 
                        `title`="ICC1", 
                        `type`="number"),
                    list(
                        `name`="icc2", 
                        `title`="ICC2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="multi",
                title="Multilevel Correlation",
                visible="(multi)",
                clearWith=list(
                    "vars"),
                refs="correlation",
                columns=list(
                    list(
                        `name`="v1", 
                        `title`="Variable1", 
                        `type`="text"),
                    list(
                        `name`="v2", 
                        `title`="Variable2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="n", 
                        `type`="integer"),
                    list(
                        `name`="low", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="high", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Correlation Heatmap",
                requiresData=TRUE,
                visible="(plot)",
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "facs",
                    "angle")))}))

multilevelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "multilevelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "multilevel",
                version = c(1,0,0),
                options = options,
                results = multilevelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multilevel Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param facs .
#' @param icc .
#' @param multi .
#' @param plot .
#' @param angle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$icc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$icc$asDF}
#'
#' \code{as.data.frame(results$icc)}
#'
#' @export
multilevel <- function(
    data,
    vars,
    facs,
    icc = TRUE,
    multi = FALSE,
    plot = FALSE,
    angle = 45) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("multilevel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(facs)) facs <- jmvcore::resolveQuo(jmvcore::enquo(facs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(facs), facs, NULL))

    for (v in facs) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- multilevelOptions$new(
        vars = vars,
        facs = facs,
        icc = icc,
        multi = multi,
        plot = plot,
        angle = angle)

    analysis <- multilevelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

