
# This file is automatically generated, you probably don't want to edit this

netcompOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "netcompOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            run = FALSE,
            dataType = "continuous",
            nPerm = 200,
            testStructure = TRUE,
            testGlobalStrength = TRUE,
            testEdges = FALSE,
            showPlots = TRUE,
            layout = "spring",
            sameLayout = TRUE,
            minimum = 0, ...) {

            super$initialize(
                package="seolmatrix",
                name="netcomp",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..run <- jmvcore::OptionAction$new(
                "run",
                run)
            private$..dataType <- jmvcore::OptionList$new(
                "dataType",
                dataType,
                options=list(
                    "continuous",
                    "binary"),
                default="continuous")
            private$..nPerm <- jmvcore::OptionInteger$new(
                "nPerm",
                nPerm,
                default=200)
            private$..testStructure <- jmvcore::OptionBool$new(
                "testStructure",
                testStructure,
                default=TRUE)
            private$..testGlobalStrength <- jmvcore::OptionBool$new(
                "testGlobalStrength",
                testGlobalStrength,
                default=TRUE)
            private$..testEdges <- jmvcore::OptionBool$new(
                "testEdges",
                testEdges,
                default=FALSE)
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..layout <- jmvcore::OptionList$new(
                "layout",
                layout,
                options=list(
                    "spring",
                    "circle"),
                default="spring")
            private$..sameLayout <- jmvcore::OptionBool$new(
                "sameLayout",
                sameLayout,
                default=TRUE)
            private$..minimum <- jmvcore::OptionNumber$new(
                "minimum",
                minimum,
                default=0,
                min=0,
                max=1)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..run)
            self$.addOption(private$..dataType)
            self$.addOption(private$..nPerm)
            self$.addOption(private$..testStructure)
            self$.addOption(private$..testGlobalStrength)
            self$.addOption(private$..testEdges)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..layout)
            self$.addOption(private$..sameLayout)
            self$.addOption(private$..minimum)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        run = function() private$..run$value,
        dataType = function() private$..dataType$value,
        nPerm = function() private$..nPerm$value,
        testStructure = function() private$..testStructure$value,
        testGlobalStrength = function() private$..testGlobalStrength$value,
        testEdges = function() private$..testEdges$value,
        showPlots = function() private$..showPlots$value,
        layout = function() private$..layout$value,
        sameLayout = function() private$..sameLayout$value,
        minimum = function() private$..minimum$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..run = NA,
        ..dataType = NA,
        ..nPerm = NA,
        ..testStructure = NA,
        ..testGlobalStrength = NA,
        ..testEdges = NA,
        ..showPlots = NA,
        ..layout = NA,
        ..sameLayout = NA,
        ..minimum = NA)
)

netcompResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "netcompResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        groupPlots = function() private$.items[["groupPlots"]],
        summary = function() private$.items[["summary"]],
        tests = function() private$.items[["tests"]],
        edges = function() private$.items[["edges"]],
        note = function() private$.items[["note"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Group Network Comparison",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    plotGroup1 = function() private$.items[["plotGroup1"]],
                    plotGroup2 = function() private$.items[["plotGroup2"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="groupPlots",
                            title="Group Network Plots",
                            refs="NetworkComparisonTest")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="plotGroup1",
                            title="",
                            renderFun=".plotGroup1",
                            clearWith=list(
                                "vars",
                                "group",
                                "dataType",
                                "layout",
                                "minimum")))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="plotGroup2",
                            title="",
                            renderFun=".plotGroup2",
                            clearWith=list(
                                "vars",
                                "group",
                                "dataType",
                                "layout",
                                "minimum")))}))$new(options=options))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                rows=1,
                refs="NetworkComparisonTest",
                clearWith=list(
                    "vars",
                    "group",
                    "nPerm",
                    "dataType"),
                columns=list(
                    list(
                        `name`="nVars", 
                        `title`="Variables", 
                        `type`="integer"),
                    list(
                        `name`="groupVar", 
                        `title`="Grouping Variable", 
                        `type`="text"),
                    list(
                        `name`="group1", 
                        `title`="Group 1", 
                        `type`="text"),
                    list(
                        `name`="n1", 
                        `title`="N Group 1", 
                        `type`="integer"),
                    list(
                        `name`="group2", 
                        `title`="Group 2", 
                        `type`="text"),
                    list(
                        `name`="n2", 
                        `title`="N Group 2", 
                        `type`="integer"),
                    list(
                        `name`="permutations", 
                        `title`="Permutations", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="Invariance Tests",
                rows=0,
                refs="NetworkComparisonTest",
                clearWith=list(
                    "vars",
                    "group",
                    "nPerm",
                    "dataType"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="edges",
                title="Edge Differences",
                rows=0,
                refs="NetworkComparisonTest",
                clearWith=list(
                    "vars",
                    "group",
                    "nPerm",
                    "testEdges",
                    "dataType"),
                columns=list(
                    list(
                        `name`="node1", 
                        `title`="Node 1", 
                        `type`="text"),
                    list(
                        `name`="node2", 
                        `title`="Node 2", 
                        `type`="text"),
                    list(
                        `name`="diff", 
                        `title`="Test statistic E", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="note",
                title="Note"))}))

netcompBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "netcompBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "netcomp",
                version = c(1,0,0),
                options = options,
                results = netcompResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Group Network Comparison
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param run .
#' @param dataType .
#' @param nPerm .
#' @param testStructure .
#' @param testGlobalStrength .
#' @param testEdges .
#' @param showPlots .
#' @param layout .
#' @param sameLayout .
#' @param minimum .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$groupPlots$plotGroup1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$groupPlots$plotGroup2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$edges} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$note} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
netcomp <- function(
    data,
    vars,
    group,
    run = FALSE,
    dataType = "continuous",
    nPerm = 200,
    testStructure = TRUE,
    testGlobalStrength = TRUE,
    testEdges = FALSE,
    showPlots = TRUE,
    layout = "spring",
    sameLayout = TRUE,
    minimum = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("netcomp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- netcompOptions$new(
        vars = vars,
        group = group,
        run = run,
        dataType = dataType,
        nPerm = nPerm,
        testStructure = testStructure,
        testGlobalStrength = testGlobalStrength,
        testEdges = testEdges,
        showPlots = showPlots,
        layout = layout,
        sameLayout = sameLayout,
        minimum = minimum)

    analysis <- netcompClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

