
# This file is automatically generated, you probably don't want to edit this

partialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            ctrlvars = NULL,
            type = "pearson",
            missing = "pairwise.complete.obs",
            sidSig = "twotailed",
            scale = "raw0",
            shwSig = FALSE,
            flgSig = TRUE,
            cen = FALSE,
            plot = FALSE,
            model = "glasso",
            layout = "spring",
            shape = "circle",
            plot2 = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            angle = 0,
            robust = FALSE,
            method = "percentage",
            plot3 = FALSE,
            angle1 = 45,
            width3 = 500,
            height3 = 500, ...) {

            super$initialize(
                package="seolmatrix",
                name="partial",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..ctrlvars <- jmvcore::OptionVariables$new(
                "ctrlvars",
                ctrlvars)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson")
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "complete.obs",
                    "pairwise.complete.obs"),
                default="pairwise.complete.obs")
            private$..sidSig <- jmvcore::OptionList$new(
                "sidSig",
                sidSig,
                options=list(
                    "onetailed",
                    "twotailed"),
                default="twotailed")
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "raw0",
                    "raw",
                    "z-scores",
                    "relative"),
                default="raw0")
            private$..shwSig <- jmvcore::OptionBool$new(
                "shwSig",
                shwSig,
                default=FALSE)
            private$..flgSig <- jmvcore::OptionBool$new(
                "flgSig",
                flgSig,
                default=TRUE)
            private$..cen <- jmvcore::OptionBool$new(
                "cen",
                cen,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "glasso",
                    "pcor",
                    "cor"),
                default="glasso")
            private$..layout <- jmvcore::OptionList$new(
                "layout",
                layout,
                options=list(
                    "spring",
                    "circle",
                    "groups",
                    "circular"),
                default="spring")
            private$..shape <- jmvcore::OptionList$new(
                "shape",
                shape,
                options=list(
                    "circle",
                    "square",
                    "triangle",
                    "diamond",
                    "ellipse",
                    "heart"),
                default="circle")
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..robust <- jmvcore::OptionBool$new(
                "robust",
                robust,
                default=FALSE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "percentage",
                    "biweight"),
                default="percentage")
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..angle1 <- jmvcore::OptionNumber$new(
                "angle1",
                angle1,
                min=0,
                max=90,
                default=45)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..ctrlvars)
            self$.addOption(private$..type)
            self$.addOption(private$..missing)
            self$.addOption(private$..sidSig)
            self$.addOption(private$..scale)
            self$.addOption(private$..shwSig)
            self$.addOption(private$..flgSig)
            self$.addOption(private$..cen)
            self$.addOption(private$..plot)
            self$.addOption(private$..model)
            self$.addOption(private$..layout)
            self$.addOption(private$..shape)
            self$.addOption(private$..plot2)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..angle)
            self$.addOption(private$..robust)
            self$.addOption(private$..method)
            self$.addOption(private$..plot3)
            self$.addOption(private$..angle1)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
        }),
    active = list(
        vars = function() private$..vars$value,
        ctrlvars = function() private$..ctrlvars$value,
        type = function() private$..type$value,
        missing = function() private$..missing$value,
        sidSig = function() private$..sidSig$value,
        scale = function() private$..scale$value,
        shwSig = function() private$..shwSig$value,
        flgSig = function() private$..flgSig$value,
        cen = function() private$..cen$value,
        plot = function() private$..plot$value,
        model = function() private$..model$value,
        layout = function() private$..layout$value,
        shape = function() private$..shape$value,
        plot2 = function() private$..plot2$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        angle = function() private$..angle$value,
        robust = function() private$..robust$value,
        method = function() private$..method$value,
        plot3 = function() private$..plot3$value,
        angle1 = function() private$..angle1$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value),
    private = list(
        ..vars = NA,
        ..ctrlvars = NA,
        ..type = NA,
        ..missing = NA,
        ..sidSig = NA,
        ..scale = NA,
        ..shwSig = NA,
        ..flgSig = NA,
        ..cen = NA,
        ..plot = NA,
        ..model = NA,
        ..layout = NA,
        ..shape = NA,
        ..plot2 = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..angle = NA,
        ..robust = NA,
        ..method = NA,
        ..plot3 = NA,
        ..angle1 = NA,
        ..width3 = NA,
        ..height3 = NA)
)

partialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text2 = function() private$.items[["text2"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]],
        plot2 = function() private$.items[["plot2"]],
        cen = function() private$.items[["cen"]],
        robust = function() private$.items[["robust"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text2",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="`Correlation matrix - ${type}`",
                visible="(matrix)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "type",
                    "missing",
                    "shwSig",
                    "sidSig"),
                refs="seolmatrix",
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="r", 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".name[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".stat[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="p-value", 
                        `visible`="(shwSig)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Network plot",
                renderFun=".plot",
                visible="(plot)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "width",
                    "height",
                    "model",
                    "layout",
                    "shape")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Centrality plot ",
                renderFun=".plot2",
                visible="(plot2)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "scale",
                    "width1",
                    "height1",
                    "angle")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cen",
                title="Centrality",
                visible="(cen)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "scale"),
                refs="qgraph",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="clo", 
                        `title`="Closeness"),
                    list(
                        `name`="bet", 
                        `title`="Betweeness"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="robust",
                title="`Robust correlation - ${method}`",
                visible="(robust)",
                clearWith=list(
                    "vars"),
                refs="correlation",
                columns=list(
                    list(
                        `name`="v1", 
                        `title`="Variable1", 
                        `type`="text"),
                    list(
                        `name`="v2", 
                        `title`="Variable2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="n", 
                        `type`="integer"),
                    list(
                        `name`="low", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="high", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Correlation Heatmap",
                requiresData=TRUE,
                visible="(plot3)",
                renderFun=".plot3",
                clearWith=list(
                    "vars",
                    "angle1",
                    "method",
                    "width3",
                    "height3")))}))

partialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "partial",
                version = c(1,0,0),
                options = options,
                results = partialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Partial Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param ctrlvars .
#' @param type .
#' @param missing .
#' @param sidSig .
#' @param scale .
#' @param shwSig .
#' @param flgSig .
#' @param cen .
#' @param plot .
#' @param model .
#' @param layout .
#' @param shape .
#' @param plot2 .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param angle .
#' @param robust .
#' @param method .
#' @param plot3 .
#' @param angle1 .
#' @param width3 .
#' @param height3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$robust} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
partial <- function(
    data,
    vars,
    ctrlvars,
    type = "pearson",
    missing = "pairwise.complete.obs",
    sidSig = "twotailed",
    scale = "raw0",
    shwSig = FALSE,
    flgSig = TRUE,
    cen = FALSE,
    plot = FALSE,
    model = "glasso",
    layout = "spring",
    shape = "circle",
    plot2 = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    angle = 0,
    robust = FALSE,
    method = "percentage",
    plot3 = FALSE,
    angle1 = 45,
    width3 = 500,
    height3 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("partial requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(ctrlvars)) ctrlvars <- jmvcore::resolveQuo(jmvcore::enquo(ctrlvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(ctrlvars), ctrlvars, NULL))


    options <- partialOptions$new(
        vars = vars,
        ctrlvars = ctrlvars,
        type = type,
        missing = missing,
        sidSig = sidSig,
        scale = scale,
        shwSig = shwSig,
        flgSig = flgSig,
        cen = cen,
        plot = plot,
        model = model,
        layout = layout,
        shape = shape,
        plot2 = plot2,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        angle = angle,
        robust = robust,
        method = method,
        plot3 = plot3,
        angle1 = angle1,
        width3 = width3,
        height3 = height3)

    analysis <- partialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

