
# This file is automatically generated, you probably don't want to edit this

partialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            ctrlvars = NULL,
            sidSig = "twotailed",
            scale = "raw0",
            scale1 = "raw0",
            shwSig = FALSE,
            flgSig = TRUE,
            plot = TRUE,
            model = "glasso",
            layout = "spring",
            shape = "circle",
            plot2 = FALSE,
            plot3 = FALSE,
            ebic = FALSE,
            pm = FALSE,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width2 = 500,
            height2 = 500,
            angle = 0,
            angle1 = 0, ...) {

            super$initialize(
                package="seolmatrix",
                name="partial",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ctrlvars <- jmvcore::OptionVariables$new(
                "ctrlvars",
                ctrlvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sidSig <- jmvcore::OptionList$new(
                "sidSig",
                sidSig,
                options=list(
                    "onetailed",
                    "twotailed"),
                default="twotailed")
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "raw0",
                    "raw",
                    "z-scores",
                    "relative"),
                default="raw0")
            private$..scale1 <- jmvcore::OptionList$new(
                "scale1",
                scale1,
                options=list(
                    "raw0",
                    "raw",
                    "z-scores",
                    "relative"),
                default="raw0")
            private$..shwSig <- jmvcore::OptionBool$new(
                "shwSig",
                shwSig,
                default=FALSE)
            private$..flgSig <- jmvcore::OptionBool$new(
                "flgSig",
                flgSig,
                default=TRUE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "glasso",
                    "pcor",
                    "cor"),
                default="glasso")
            private$..layout <- jmvcore::OptionList$new(
                "layout",
                layout,
                options=list(
                    "spring",
                    "circle",
                    "groups",
                    "circular"),
                default="spring")
            private$..shape <- jmvcore::OptionList$new(
                "shape",
                shape,
                options=list(
                    "circle",
                    "square",
                    "triangle",
                    "diamond",
                    "ellipse",
                    "heart"),
                default="circle")
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..ebic <- jmvcore::OptionBool$new(
                "ebic",
                ebic,
                default=FALSE)
            private$..pm <- jmvcore::OptionBool$new(
                "pm",
                pm,
                default=FALSE)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..angle1 <- jmvcore::OptionNumber$new(
                "angle1",
                angle1,
                min=0,
                max=90,
                default=0)

            self$.addOption(private$..vars)
            self$.addOption(private$..ctrlvars)
            self$.addOption(private$..sidSig)
            self$.addOption(private$..scale)
            self$.addOption(private$..scale1)
            self$.addOption(private$..shwSig)
            self$.addOption(private$..flgSig)
            self$.addOption(private$..plot)
            self$.addOption(private$..model)
            self$.addOption(private$..layout)
            self$.addOption(private$..shape)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..ebic)
            self$.addOption(private$..pm)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..angle)
            self$.addOption(private$..angle1)
        }),
    active = list(
        vars = function() private$..vars$value,
        ctrlvars = function() private$..ctrlvars$value,
        sidSig = function() private$..sidSig$value,
        scale = function() private$..scale$value,
        scale1 = function() private$..scale1$value,
        shwSig = function() private$..shwSig$value,
        flgSig = function() private$..flgSig$value,
        plot = function() private$..plot$value,
        model = function() private$..model$value,
        layout = function() private$..layout$value,
        shape = function() private$..shape$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        ebic = function() private$..ebic$value,
        pm = function() private$..pm$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        angle = function() private$..angle$value,
        angle1 = function() private$..angle1$value),
    private = list(
        ..vars = NA,
        ..ctrlvars = NA,
        ..sidSig = NA,
        ..scale = NA,
        ..scale1 = NA,
        ..shwSig = NA,
        ..flgSig = NA,
        ..plot = NA,
        ..model = NA,
        ..layout = NA,
        ..shape = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..ebic = NA,
        ..pm = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..angle = NA,
        ..angle1 = NA)
)

partialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]],
        text = function() private$.items[["text"]],
        text1 = function() private$.items[["text1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Correlation Matrix",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "shwSig",
                    "sidSig"),
                refs="seolmatrix",
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="r", 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".name[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".stat[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="p-value", 
                        `visible`="(shwSig)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Network plot",
                renderFun=".plot",
                visible="(plot)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "width",
                    "height",
                    "model",
                    "layout",
                    "shape")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Centrality plot ",
                renderFun=".plot2",
                visible="(plot2)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "scale",
                    "width1",
                    "height1",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Clustering plot ",
                renderFun=".plot3",
                visible="(plot3)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "ctrlvars",
                    "scale1",
                    "width2",
                    "height2",
                    "angle1")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="EBICglasso matrix",
                clearWith=list(
                    "vars",
                    "ctrlvars")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title="Partial matrix",
                clearWith=list(
                    "vars",
                    "ctrlvars")))}))

partialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "partialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "partial",
                version = c(1,0,0),
                options = options,
                results = partialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Partial Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param ctrlvars .
#' @param sidSig .
#' @param scale .
#' @param scale1 .
#' @param shwSig .
#' @param flgSig .
#' @param plot .
#' @param model .
#' @param layout .
#' @param shape .
#' @param plot2 .
#' @param plot3 .
#' @param ebic .
#' @param pm .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width2 .
#' @param height2 .
#' @param angle .
#' @param angle1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab correlation matrix table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
partial <- function(
    data,
    vars,
    ctrlvars,
    sidSig = "twotailed",
    scale = "raw0",
    scale1 = "raw0",
    shwSig = FALSE,
    flgSig = TRUE,
    plot = TRUE,
    model = "glasso",
    layout = "spring",
    shape = "circle",
    plot2 = FALSE,
    plot3 = FALSE,
    ebic = FALSE,
    pm = FALSE,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width2 = 500,
    height2 = 500,
    angle = 0,
    angle1 = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("partial requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(ctrlvars)) ctrlvars <- jmvcore::resolveQuo(jmvcore::enquo(ctrlvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(ctrlvars), ctrlvars, NULL))


    options <- partialOptions$new(
        vars = vars,
        ctrlvars = ctrlvars,
        sidSig = sidSig,
        scale = scale,
        scale1 = scale1,
        shwSig = shwSig,
        flgSig = flgSig,
        plot = plot,
        model = model,
        layout = layout,
        shape = shape,
        plot2 = plot2,
        plot3 = plot3,
        ebic = ebic,
        pm = pm,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width2 = width2,
        height2 = height2,
        angle = angle,
        angle1 = angle1)

    analysis <- partialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

