
# This file is automatically generated, you probably don't want to edit this

partialOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "partialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            ctrlvars = NULL,
            sidSig = "twotailed",
            shwSig = TRUE,
            flgSig = TRUE,
            ggm = FALSE, ...) {

            super$initialize(
                package='seolmatrix',
                name='partial',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ctrlvars <- jmvcore::OptionVariables$new(
                "ctrlvars",
                ctrlvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sidSig <- jmvcore::OptionList$new(
                "sidSig",
                sidSig,
                options=list(
                    "onetailed",
                    "twotailed"),
                default="twotailed")
            private$..shwSig <- jmvcore::OptionBool$new(
                "shwSig",
                shwSig,
                default=TRUE)
            private$..flgSig <- jmvcore::OptionBool$new(
                "flgSig",
                flgSig,
                default=TRUE)
            private$..ggm <- jmvcore::OptionBool$new(
                "ggm",
                ggm,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..ctrlvars)
            self$.addOption(private$..sidSig)
            self$.addOption(private$..shwSig)
            self$.addOption(private$..flgSig)
            self$.addOption(private$..ggm)
        }),
    active = list(
        vars = function() private$..vars$value,
        ctrlvars = function() private$..ctrlvars$value,
        sidSig = function() private$..sidSig$value,
        shwSig = function() private$..shwSig$value,
        flgSig = function() private$..flgSig$value,
        ggm = function() private$..ggm$value),
    private = list(
        ..vars = NA,
        ..ctrlvars = NA,
        ..sidSig = NA,
        ..shwSig = NA,
        ..flgSig = NA,
        ..ggm = NA)
)

partialResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Partial Correlation")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Correlation Matrix",
                rows="(vars)",
                clearWith=list(
                    "shwSig",
                    "sidSig"),
                refs="cormatrix",
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="r"),
                    list(
                        `name`=".name[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE, 
                        `visible`="(shwSig)"),
                    list(
                        `name`=".stat[rp]", 
                        `title`="", 
                        `type`="text", 
                        `content`="p-value", 
                        `visible`="(shwSig)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible=TRUE))}))

partialBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "partialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'seolmatrix',
                name = 'partial',
                version = c(1,0,0),
                options = options,
                results = partialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Partial Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param ctrlvars .
#' @param sidSig .
#' @param shwSig .
#' @param flgSig .
#' @param ggm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab correlation matrix table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
partial <- function(
    data,
    vars,
    ctrlvars,
    sidSig = "twotailed",
    shwSig = TRUE,
    flgSig = TRUE,
    ggm = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('partial requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(ctrlvars)) ctrlvars <- jmvcore::resolveQuo(jmvcore::enquo(ctrlvars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(ctrlvars), ctrlvars, NULL))


    options <- partialOptions$new(
        vars = vars,
        ctrlvars = ctrlvars,
        sidSig = sidSig,
        shwSig = shwSig,
        flgSig = flgSig,
        ggm = ggm)

    analysis <- partialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
