
# This file is automatically generated, you probably don't want to edit this

polyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "polyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            polychoric = TRUE,
            ggm = FALSE,
            par = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="poly",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..polychoric <- jmvcore::OptionBool$new(
                "polychoric",
                polychoric,
                default=TRUE)
            private$..ggm <- jmvcore::OptionBool$new(
                "ggm",
                ggm,
                default=FALSE)
            private$..par <- jmvcore::OptionBool$new(
                "par",
                par,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..polychoric)
            self$.addOption(private$..ggm)
            self$.addOption(private$..par)
        }),
    active = list(
        vars = function() private$..vars$value,
        polychoric = function() private$..polychoric$value,
        ggm = function() private$..ggm$value,
        par = function() private$..par$value),
    private = list(
        ..vars = NA,
        ..polychoric = NA,
        ..ggm = NA,
        ..par = NA)
)

polyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "polyResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polychoric Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Polychoric Correlation",
                visible="(matrix)",
                refs="psych",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(ggm)",
                refs="qgraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Partial plot",
                width=500,
                height=500,
                renderFun=".plot1",
                visible="(par)",
                refs="qgraph"))}))

polyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "polyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "poly",
                version = c(1,0,0),
                options = options,
                results = polyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Polychoric Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param polychoric .
#' @param ggm .
#' @param par .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
poly <- function(
    data,
    vars,
    polychoric = TRUE,
    ggm = FALSE,
    par = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("poly requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- polyOptions$new(
        vars = vars,
        polychoric = polychoric,
        ggm = ggm,
        par = par)

    analysis <- polyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

