
# This file is automatically generated, you probably don't want to edit this

rankOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "rankOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            spearman = TRUE,
            ggm = FALSE,
            par = FALSE, ...) {

            super$initialize(
                package='seolmatrix',
                name='rank',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..spearman <- jmvcore::OptionBool$new(
                "spearman",
                spearman,
                default=TRUE)
            private$..ggm <- jmvcore::OptionBool$new(
                "ggm",
                ggm,
                default=FALSE)
            private$..par <- jmvcore::OptionBool$new(
                "par",
                par,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..spearman)
            self$.addOption(private$..ggm)
            self$.addOption(private$..par)
        }),
    active = list(
        vars = function() private$..vars$value,
        spearman = function() private$..spearman$value,
        ggm = function() private$..ggm$value,
        par = function() private$..par$value),
    private = list(
        ..vars = NA,
        ..spearman = NA,
        ..ggm = NA,
        ..par = NA)
)

rankResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Spearman Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="Spearman Correlation",
                rows="(vars)",
                refs="psych",
                columns=list(
                    list(
                        `name`=".name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(ggm)",
                refs="qgraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Partial plot",
                width=500,
                height=500,
                renderFun=".plot1",
                visible="(par)",
                refs="qgraph"))}))

rankBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "rankBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'seolmatrix',
                name = 'rank',
                version = c(1,0,0),
                options = options,
                results = rankResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Spearman Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param spearman .
#' @param ggm .
#' @param par .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab correlation matrix table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
rank <- function(
    data,
    vars,
    spearman = TRUE,
    ggm = FALSE,
    par = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('rank requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- rankOptions$new(
        vars = vars,
        spearman = spearman,
        ggm = ggm,
        par = par)

    analysis <- rankClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
