
# This file is automatically generated, you probably don't want to edit this

rankOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rankOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            type = "spearman",
            sigStars = FALSE,
            pmatrix = FALSE,
            tau = FALSE,
            scale = "raw0",
            plot = FALSE,
            plot1 = FALSE,
            plot2 = FALSE,
            plot3 = FALSE,
            angle = 0,
            method = "circle",
            type1 = "lower", ...) {

            super$initialize(
                package="seolmatrix",
                name="rank",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "spearman",
                    "polychoric",
                    "tetrachoric"),
                default="spearman")
            private$..sigStars <- jmvcore::OptionBool$new(
                "sigStars",
                sigStars,
                default=FALSE)
            private$..pmatrix <- jmvcore::OptionBool$new(
                "pmatrix",
                pmatrix,
                default=FALSE)
            private$..tau <- jmvcore::OptionBool$new(
                "tau",
                tau,
                default=FALSE)
            private$..scale <- jmvcore::OptionList$new(
                "scale",
                scale,
                options=list(
                    "raw0",
                    "raw",
                    "z-scores",
                    "relative"),
                default="raw0")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "circle",
                    "square",
                    "ellipse",
                    "number",
                    "shade",
                    "color",
                    "pie"),
                default="circle")
            private$..type1 <- jmvcore::OptionList$new(
                "type1",
                type1,
                options=list(
                    "full",
                    "lower",
                    "upper"),
                default="lower")

            self$.addOption(private$..vars)
            self$.addOption(private$..type)
            self$.addOption(private$..sigStars)
            self$.addOption(private$..pmatrix)
            self$.addOption(private$..tau)
            self$.addOption(private$..scale)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..angle)
            self$.addOption(private$..method)
            self$.addOption(private$..type1)
        }),
    active = list(
        vars = function() private$..vars$value,
        type = function() private$..type$value,
        sigStars = function() private$..sigStars$value,
        pmatrix = function() private$..pmatrix$value,
        tau = function() private$..tau$value,
        scale = function() private$..scale$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value,
        plot2 = function() private$..plot2$value,
        plot3 = function() private$..plot3$value,
        angle = function() private$..angle$value,
        method = function() private$..method$value,
        type1 = function() private$..type1$value),
    private = list(
        ..vars = NA,
        ..type = NA,
        ..sigStars = NA,
        ..pmatrix = NA,
        ..tau = NA,
        ..scale = NA,
        ..plot = NA,
        ..plot1 = NA,
        ..plot2 = NA,
        ..plot3 = NA,
        ..angle = NA,
        ..method = NA,
        ..type1 = NA)
)

rankResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rankResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        matrix = function() private$.items[["matrix"]],
        pmatrix = function() private$.items[["pmatrix"]],
        tau = function() private$.items[["tau"]],
        plot3 = function() private$.items[["plot3"]],
        plot = function() private$.items[["plot"]],
        plot2 = function() private$.items[["plot2"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ordinal Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="matrix",
                title="`Correlation matrix - ${type}`",
                visible="(matrix)",
                clearWith=list(
                    "vars",
                    "type"),
                refs="psych",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pmatrix",
                title="`p-value matrix - ${type}`",
                visible="(pmatrix)",
                clearWith=list(
                    "vars",
                    "type"),
                refs="stats",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tau",
                title="Thresholds (\u03C4) by variable",
                visible="(tau)",
                clearWith=list(
                    "vars",
                    "type"),
                refs="psych",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="tau", 
                        `title`="Tau", 
                        `type`="number"),
                    list(
                        `name`="p1", 
                        `title`="Pr(Y = 1)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Matrix plot",
                renderFun=".plot3",
                visible="(plot3)",
                refs="corrplot",
                clearWith=list(
                    "vars",
                    "type",
                    "type1",
                    "method",
                    "width3",
                    "height3")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                renderFun=".plot",
                visible="(plot)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "type")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Centrality plot ",
                renderFun=".plot2",
                visible="(plot2)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "type",
                    "scale",
                    "angle")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Partial plot",
                renderFun=".plot1",
                visible="(plot1)",
                refs="qgraph",
                clearWith=list(
                    "vars",
                    "type")))}))

rankBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rankBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "rank",
                version = c(1,0,0),
                options = options,
                results = rankResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Ordinal Correlation
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param type .
#' @param sigStars .
#' @param pmatrix .
#' @param tau .
#' @param scale .
#' @param plot .
#' @param plot1 .
#' @param plot2 .
#' @param plot3 .
#' @param angle .
#' @param method .
#' @param type1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$matrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pmatrix} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tau} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$matrix$asDF}
#'
#' \code{as.data.frame(results$matrix)}
#'
#' @export
rank <- function(
    data,
    vars,
    type = "spearman",
    sigStars = FALSE,
    pmatrix = FALSE,
    tau = FALSE,
    scale = "raw0",
    plot = FALSE,
    plot1 = FALSE,
    plot2 = FALSE,
    plot3 = FALSE,
    angle = 0,
    method = "circle",
    type1 = "lower") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rank requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rankOptions$new(
        vars = vars,
        type = type,
        sigStars = sigStars,
        pmatrix = pmatrix,
        tau = tau,
        scale = scale,
        plot = plot,
        plot1 = plot1,
        plot2 = plot2,
        plot3 = plot3,
        angle = angle,
        method = method,
        type1 = type1)

    analysis <- rankClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

