
# This file is automatically generated, you probably don't want to edit this

raterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            model = "oneway",
            type = "agreement",
            unit = "single",
            interrater = TRUE,
            icc = FALSE,
            bicc = FALSE,
            ic = TRUE,
            ftest = TRUE,
            ggm = FALSE,
            par = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="rater",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "oneway",
                    "twoway"),
                default="oneway")
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "agreement",
                    "consistency"),
                default="agreement")
            private$..unit <- jmvcore::OptionList$new(
                "unit",
                unit,
                options=list(
                    "single",
                    "average"),
                default="single")
            private$..interrater <- jmvcore::OptionBool$new(
                "interrater",
                interrater,
                default=TRUE)
            private$..icc <- jmvcore::OptionBool$new(
                "icc",
                icc,
                default=FALSE)
            private$..bicc <- jmvcore::OptionBool$new(
                "bicc",
                bicc,
                default=FALSE)
            private$..ic <- jmvcore::OptionBool$new(
                "ic",
                ic,
                default=TRUE)
            private$..ftest <- jmvcore::OptionBool$new(
                "ftest",
                ftest,
                default=TRUE)
            private$..ggm <- jmvcore::OptionBool$new(
                "ggm",
                ggm,
                default=FALSE)
            private$..par <- jmvcore::OptionBool$new(
                "par",
                par,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..model)
            self$.addOption(private$..type)
            self$.addOption(private$..unit)
            self$.addOption(private$..interrater)
            self$.addOption(private$..icc)
            self$.addOption(private$..bicc)
            self$.addOption(private$..ic)
            self$.addOption(private$..ftest)
            self$.addOption(private$..ggm)
            self$.addOption(private$..par)
        }),
    active = list(
        vars = function() private$..vars$value,
        model = function() private$..model$value,
        type = function() private$..type$value,
        unit = function() private$..unit$value,
        interrater = function() private$..interrater$value,
        icc = function() private$..icc$value,
        bicc = function() private$..bicc$value,
        ic = function() private$..ic$value,
        ftest = function() private$..ftest$value,
        ggm = function() private$..ggm$value,
        par = function() private$..par$value),
    private = list(
        ..vars = NA,
        ..model = NA,
        ..type = NA,
        ..unit = NA,
        ..interrater = NA,
        ..icc = NA,
        ..bicc = NA,
        ..ic = NA,
        ..ftest = NA,
        ..ggm = NA,
        ..par = NA)
)

raterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raterResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        interrater = function() private$.items[["interrater"]],
        icc = function() private$.items[["icc"]],
        bicc = function() private$.items[["bicc"]],
        ic = function() private$.items[["ic"]],
        ftest = function() private$.items[["ftest"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Rater Reliability",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="interrater",
                title="Interrater Reliability",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="irr",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Light's Kappa"),
                    list(
                        `name`="n", 
                        `type`="number"),
                    list(
                        `name`="rater", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `type`="number"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="icc",
                title="Intraclass correlation coefficient",
                visible="(icc)",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="psy",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Value"),
                    list(
                        `name`="Subjects", 
                        `type`="number"),
                    list(
                        `name`="Raters", 
                        `type`="number"),
                    list(
                        `name`="Subject variance", 
                        `type`="number"),
                    list(
                        `name`="Rater variance", 
                        `type`="number"),
                    list(
                        `name`="Residual variance", 
                        `type`="number"),
                    list(
                        `name`="Consistency", 
                        `type`="number"),
                    list(
                        `name`="Agreement", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="bicc",
                title="Bootstrap Agreement",
                visible="(bicc)",
                rows=1,
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Agreement"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ic",
                title="Intraclass correlation coefficient(ICC)",
                rows=1,
                visible="(ic)",
                clearWith=list(
                    "vars",
                    "model",
                    "type",
                    "unit"),
                refs="irr",
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="unit", 
                        `title`="Unit", 
                        `type`="text"),
                    list(
                        `name`="sub", 
                        `title`="Subjects", 
                        `type`="integer"),
                    list(
                        `name`="raters", 
                        `title`="Raters", 
                        `type`="integer"),
                    list(
                        `name`="icc", 
                        `title`="ICC", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ftest",
                title="F test for ICC",
                rows=1,
                visible="(ftest)",
                clearWith=list(
                    "vars",
                    "model",
                    "type",
                    "unit"),
                refs="irr",
                columns=list(
                    list(
                        `name`="icc", 
                        `title`="ICC", 
                        `type`="number"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="number"),
                    list(
                        `name`="p1", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto, number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(ggm)",
                refs="qgraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Partial plot",
                width=500,
                height=500,
                renderFun=".plot1",
                visible="(par)",
                refs="qgraph"))}))

raterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "raterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "rater",
                version = c(1,0,0),
                options = options,
                results = raterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Rater Reliability
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param model .
#' @param type .
#' @param unit .
#' @param interrater .
#' @param icc .
#' @param bicc .
#' @param ic .
#' @param ftest .
#' @param ggm .
#' @param par .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interrater} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$icc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bicc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ic} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ftest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$interrater$asDF}
#'
#' \code{as.data.frame(results$interrater)}
#'
#' @export
rater <- function(
    data,
    vars,
    model = "oneway",
    type = "agreement",
    unit = "single",
    interrater = TRUE,
    icc = FALSE,
    bicc = FALSE,
    ic = TRUE,
    ftest = TRUE,
    ggm = FALSE,
    par = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rater requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- raterOptions$new(
        vars = vars,
        model = model,
        type = type,
        unit = unit,
        interrater = interrater,
        icc = icc,
        bicc = bicc,
        ic = ic,
        ftest = ftest,
        ggm = ggm,
        par = par)

    analysis <- raterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

