
# This file is automatically generated, you probably don't want to edit this

raterOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "raterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            interrater = TRUE,
            ggm = FALSE, ...) {

            super$initialize(
                package='seolmatrix',
                name='rater',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..interrater <- jmvcore::OptionBool$new(
                "interrater",
                interrater,
                default=TRUE)
            private$..ggm <- jmvcore::OptionBool$new(
                "ggm",
                ggm,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..interrater)
            self$.addOption(private$..ggm)
        }),
    active = list(
        vars = function() private$..vars$value,
        interrater = function() private$..interrater$value,
        ggm = function() private$..ggm$value),
    private = list(
        ..vars = NA,
        ..interrater = NA,
        ..ggm = NA)
)

raterResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        interrater = function() private$.items[["interrater"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Rater Reliability")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="seolmatrix"))
            self$add(jmvcore::Table$new(
                options=options,
                name="interrater",
                title="Interrater Reliability",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="irr",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="Light's Kappa"),
                    list(
                        `name`="n", 
                        `type`="number"),
                    list(
                        `name`="rater", 
                        `type`="number"),
                    list(
                        `name`="statistic"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Gaussian Graphical Model",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(ggm)",
                refs="qgraph"))}))

raterBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "raterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'seolmatrix',
                name = 'rater',
                version = c(1,0,0),
                options = options,
                results = raterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Rater Reliability
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param interrater .
#' @param ggm .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interrater} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$interrater$asDF}
#'
#' \code{as.data.frame(results$interrater)}
#'
#' @export
rater <- function(
    data,
    vars,
    interrater = TRUE,
    ggm = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('rater requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- raterOptions$new(
        vars = vars,
        interrater = interrater,
        ggm = ggm)

    analysis <- raterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
