
# This file is automatically generated, you probably don't want to edit this

rmcOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmcOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            id = NULL,
            dep = NULL,
            covs = NULL,
            cc = TRUE,
            ccp = FALSE, ...) {

            super$initialize(
                package="seolmatrix",
                name="rmc",
                requiresData=TRUE,
                ...)

            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariable$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=TRUE)
            private$..ccp <- jmvcore::OptionBool$new(
                "ccp",
                ccp,
                default=FALSE)

            self$.addOption(private$..id)
            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..cc)
            self$.addOption(private$..ccp)
        }),
    active = list(
        id = function() private$..id$value,
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        cc = function() private$..cc$value,
        ccp = function() private$..ccp$value),
    private = list(
        ..id = NA,
        ..dep = NA,
        ..covs = NA,
        ..cc = NA,
        ..ccp = NA)
)

rmcResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmcResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        cc = function() private$.items[["cc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Repeated Measures Correlation",
                refs="seolmatrix")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Repeated Measures Correlation"))
            self$add(jmvcore::Table$new(
                options=options,
                name="cc",
                title="Correlation coefficient",
                rows=1,
                refs="rmcorr",
                clearWith=list(
                    "id",
                    "dep",
                    "covs"),
                columns=list(
                    list(
                        `name`="r", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))}))

rmcBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "rmcBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "seolmatrix",
                name = "rmc",
                version = c(1,0,0),
                options = options,
                results = rmcResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Repeated Measures Correlation
#'
#' 
#' @param data .
#' @param id .
#' @param dep .
#' @param covs .
#' @param cc .
#' @param ccp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cc} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cc$asDF}
#'
#' \code{as.data.frame(results$cc)}
#'
#' @export
rmc <- function(
    data,
    id,
    dep,
    covs,
    cc = TRUE,
    ccp = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rmc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in id) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- rmcOptions$new(
        id = id,
        dep = dep,
        covs = covs,
        cc = cc,
        ccp = ccp)

    analysis <- rmcClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

